// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : ble_8bit_gain.v
// Device     : Unknown
// LiteX sha1 : --------
// Date       : 2025-11-29 14:35:46
//------------------------------------------------------------------------------

`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module ble_8bit_gain (
    input  wire          clock,
    input  wire          enable,
    input  wire   [15:0] i_stream0_i,
    input  wire   [15:0] i_stream0_q,
    input  wire          i_stream0_v,
    input  wire   [15:0] i_stream1_i,
    input  wire   [15:0] i_stream1_q,
    input  wire          i_stream1_v,
    output wire   [15:0] o_stream0_i,
    output wire   [15:0] o_stream0_q,
    output wire          o_stream0_v,
    output reg    [15:0] o_stream1_i,
    output reg    [15:0] o_stream1_q,
    output reg           o_stream1_v,
    input  wire          reset
);


//------------------------------------------------------------------------------
// Hierarchy
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
// Signals
//------------------------------------------------------------------------------

wire   [15:0] complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy0;
wire   [18:0] complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy1;
wire   [15:0] complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy10;
wire   [18:0] complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy11;
wire   [15:0] complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy12;
wire   [18:0] complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy13;
wire   [15:0] complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy14;
wire   [18:0] complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy15;
wire   [15:0] complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy2;
wire   [18:0] complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy3;
wire   [15:0] complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy4;
wire   [18:0] complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy5;
wire   [15:0] complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy6;
wire   [18:0] complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy7;
wire   [15:0] complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy8;
wire   [18:0] complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy9;
wire   [18:0] complexslicelowerer_complexslicelowerer_rhs_slice_proxy0;
wire   [18:0] complexslicelowerer_complexslicelowerer_rhs_slice_proxy1;
wire   [18:0] complexslicelowerer_complexslicelowerer_rhs_slice_proxy2;
wire   [18:0] complexslicelowerer_complexslicelowerer_rhs_slice_proxy3;
wire   [15:0] complexslicelowerer_complexslicelowerer_slice_proxy0;
wire   [15:0] complexslicelowerer_complexslicelowerer_slice_proxy1;
wire   [15:0] complexslicelowerer_complexslicelowerer_slice_proxy2;
wire   [15:0] complexslicelowerer_complexslicelowerer_slice_proxy3;
wire   [18:0] complexslicelowerer_rhs_slice_proxy0;
wire   [18:0] complexslicelowerer_rhs_slice_proxy1;
wire   [18:0] complexslicelowerer_rhs_slice_proxy2;
wire   [18:0] complexslicelowerer_rhs_slice_proxy3;
wire   [15:0] complexslicelowerer_slice_proxy0;
wire   [15:0] complexslicelowerer_slice_proxy1;
wire   [15:0] complexslicelowerer_slice_proxy2;
wire   [15:0] complexslicelowerer_slice_proxy3;
wire signed  [11:0] firgain_0i_d_delay;
wire signed  [27:0] firgain_0i_mul_int0;
wire signed  [27:0] firgain_0i_mul_int1;
wire signed  [27:0] firgain_0i_mul_int10;
wire signed  [27:0] firgain_0i_mul_int11;
wire signed  [27:0] firgain_0i_mul_int12;
wire signed  [27:0] firgain_0i_mul_int13;
wire signed  [27:0] firgain_0i_mul_int14;
wire signed  [27:0] firgain_0i_mul_int2;
wire signed  [27:0] firgain_0i_mul_int3;
wire signed  [27:0] firgain_0i_mul_int4;
wire signed  [27:0] firgain_0i_mul_int5;
wire signed  [27:0] firgain_0i_mul_int6;
wire signed  [27:0] firgain_0i_mul_int7;
wire signed  [27:0] firgain_0i_mul_int8;
wire signed  [27:0] firgain_0i_mul_int9;
reg  signed  [19:0] firgain_0i_mul_q0 = 20'd0;
reg  signed  [19:0] firgain_0i_mul_q1 = 20'd0;
reg  signed  [19:0] firgain_0i_mul_q10 = 20'd0;
reg  signed  [19:0] firgain_0i_mul_q11 = 20'd0;
reg  signed  [19:0] firgain_0i_mul_q12 = 20'd0;
reg  signed  [19:0] firgain_0i_mul_q13 = 20'd0;
reg  signed  [19:0] firgain_0i_mul_q14 = 20'd0;
reg  signed  [19:0] firgain_0i_mul_q2 = 20'd0;
reg  signed  [19:0] firgain_0i_mul_q3 = 20'd0;
reg  signed  [19:0] firgain_0i_mul_q4 = 20'd0;
reg  signed  [19:0] firgain_0i_mul_q5 = 20'd0;
reg  signed  [19:0] firgain_0i_mul_q6 = 20'd0;
reg  signed  [19:0] firgain_0i_mul_q7 = 20'd0;
reg  signed  [19:0] firgain_0i_mul_q8 = 20'd0;
reg  signed  [19:0] firgain_0i_mul_q9 = 20'd0;
reg  signed  [11:0] firgain_0i_ndelay0 = 12'd0;
reg  signed  [11:0] firgain_0i_ndelay1 = 12'd0;
reg  signed  [11:0] firgain_0i_ndelay10 = 12'd0;
reg  signed  [11:0] firgain_0i_ndelay11 = 12'd0;
reg  signed  [11:0] firgain_0i_ndelay12 = 12'd0;
reg  signed  [11:0] firgain_0i_ndelay13 = 12'd0;
reg  signed  [11:0] firgain_0i_ndelay14 = 12'd0;
reg  signed  [11:0] firgain_0i_ndelay2 = 12'd0;
reg  signed  [11:0] firgain_0i_ndelay3 = 12'd0;
reg  signed  [11:0] firgain_0i_ndelay4 = 12'd0;
reg  signed  [11:0] firgain_0i_ndelay5 = 12'd0;
reg  signed  [11:0] firgain_0i_ndelay6 = 12'd0;
reg  signed  [11:0] firgain_0i_ndelay7 = 12'd0;
reg  signed  [11:0] firgain_0i_ndelay8 = 12'd0;
reg  signed  [11:0] firgain_0i_ndelay9 = 12'd0;
reg  signed  [19:0] firgain_0i_nq_sum0 = 20'd0;
reg  signed  [19:0] firgain_0i_nq_sum1 = 20'd0;
reg  signed  [19:0] firgain_0i_nq_sum2 = 20'd0;
reg  signed  [19:0] firgain_0i_nq_sum3 = 20'd0;
reg  signed  [19:0] firgain_0i_nq_sum4 = 20'd0;
reg  signed  [15:0] firgain_0i_tap_c0 = 16'd52;
reg  signed  [15:0] firgain_0i_tap_c1 = 16'd65459;
reg  signed  [15:0] firgain_0i_tap_c10 = 16'd64533;
reg  signed  [15:0] firgain_0i_tap_c11 = 16'd126;
reg  signed  [15:0] firgain_0i_tap_c12 = 16'd77;
reg  signed  [15:0] firgain_0i_tap_c13 = 16'd65459;
reg  signed  [15:0] firgain_0i_tap_c14 = 16'd52;
reg  signed  [15:0] firgain_0i_tap_c2 = 16'd77;
reg  signed  [15:0] firgain_0i_tap_c3 = 16'd126;
reg  signed  [15:0] firgain_0i_tap_c4 = 16'd64533;
reg  signed  [15:0] firgain_0i_tap_c5 = 16'd3349;
reg  signed  [15:0] firgain_0i_tap_c6 = 16'd58523;
reg  signed  [15:0] firgain_0i_tap_c7 = 16'd13118;
reg  signed  [15:0] firgain_0i_tap_c8 = 16'd58523;
reg  signed  [15:0] firgain_0i_tap_c9 = 16'd3349;
wire signed  [11:0] firgain_0q_d_delay;
wire signed  [27:0] firgain_0q_mul_int0;
wire signed  [27:0] firgain_0q_mul_int1;
wire signed  [27:0] firgain_0q_mul_int10;
wire signed  [27:0] firgain_0q_mul_int11;
wire signed  [27:0] firgain_0q_mul_int12;
wire signed  [27:0] firgain_0q_mul_int13;
wire signed  [27:0] firgain_0q_mul_int14;
wire signed  [27:0] firgain_0q_mul_int2;
wire signed  [27:0] firgain_0q_mul_int3;
wire signed  [27:0] firgain_0q_mul_int4;
wire signed  [27:0] firgain_0q_mul_int5;
wire signed  [27:0] firgain_0q_mul_int6;
wire signed  [27:0] firgain_0q_mul_int7;
wire signed  [27:0] firgain_0q_mul_int8;
wire signed  [27:0] firgain_0q_mul_int9;
reg  signed  [19:0] firgain_0q_mul_q0 = 20'd0;
reg  signed  [19:0] firgain_0q_mul_q1 = 20'd0;
reg  signed  [19:0] firgain_0q_mul_q10 = 20'd0;
reg  signed  [19:0] firgain_0q_mul_q11 = 20'd0;
reg  signed  [19:0] firgain_0q_mul_q12 = 20'd0;
reg  signed  [19:0] firgain_0q_mul_q13 = 20'd0;
reg  signed  [19:0] firgain_0q_mul_q14 = 20'd0;
reg  signed  [19:0] firgain_0q_mul_q2 = 20'd0;
reg  signed  [19:0] firgain_0q_mul_q3 = 20'd0;
reg  signed  [19:0] firgain_0q_mul_q4 = 20'd0;
reg  signed  [19:0] firgain_0q_mul_q5 = 20'd0;
reg  signed  [19:0] firgain_0q_mul_q6 = 20'd0;
reg  signed  [19:0] firgain_0q_mul_q7 = 20'd0;
reg  signed  [19:0] firgain_0q_mul_q8 = 20'd0;
reg  signed  [19:0] firgain_0q_mul_q9 = 20'd0;
reg  signed  [11:0] firgain_0q_ndelay0 = 12'd0;
reg  signed  [11:0] firgain_0q_ndelay1 = 12'd0;
reg  signed  [11:0] firgain_0q_ndelay10 = 12'd0;
reg  signed  [11:0] firgain_0q_ndelay11 = 12'd0;
reg  signed  [11:0] firgain_0q_ndelay12 = 12'd0;
reg  signed  [11:0] firgain_0q_ndelay13 = 12'd0;
reg  signed  [11:0] firgain_0q_ndelay14 = 12'd0;
reg  signed  [11:0] firgain_0q_ndelay2 = 12'd0;
reg  signed  [11:0] firgain_0q_ndelay3 = 12'd0;
reg  signed  [11:0] firgain_0q_ndelay4 = 12'd0;
reg  signed  [11:0] firgain_0q_ndelay5 = 12'd0;
reg  signed  [11:0] firgain_0q_ndelay6 = 12'd0;
reg  signed  [11:0] firgain_0q_ndelay7 = 12'd0;
reg  signed  [11:0] firgain_0q_ndelay8 = 12'd0;
reg  signed  [11:0] firgain_0q_ndelay9 = 12'd0;
reg  signed  [19:0] firgain_0q_nq_sum0 = 20'd0;
reg  signed  [19:0] firgain_0q_nq_sum1 = 20'd0;
reg  signed  [19:0] firgain_0q_nq_sum2 = 20'd0;
reg  signed  [19:0] firgain_0q_nq_sum3 = 20'd0;
reg  signed  [19:0] firgain_0q_nq_sum4 = 20'd0;
reg  signed  [15:0] firgain_0q_tap_c0 = 16'd52;
reg  signed  [15:0] firgain_0q_tap_c1 = 16'd65459;
reg  signed  [15:0] firgain_0q_tap_c10 = 16'd64533;
reg  signed  [15:0] firgain_0q_tap_c11 = 16'd126;
reg  signed  [15:0] firgain_0q_tap_c12 = 16'd77;
reg  signed  [15:0] firgain_0q_tap_c13 = 16'd65459;
reg  signed  [15:0] firgain_0q_tap_c14 = 16'd52;
reg  signed  [15:0] firgain_0q_tap_c2 = 16'd77;
reg  signed  [15:0] firgain_0q_tap_c3 = 16'd126;
reg  signed  [15:0] firgain_0q_tap_c4 = 16'd64533;
reg  signed  [15:0] firgain_0q_tap_c5 = 16'd3349;
reg  signed  [15:0] firgain_0q_tap_c6 = 16'd58523;
reg  signed  [15:0] firgain_0q_tap_c7 = 16'd13118;
reg  signed  [15:0] firgain_0q_tap_c8 = 16'd58523;
reg  signed  [15:0] firgain_0q_tap_c9 = 16'd3349;
wire   [18:0] rhs_slice_proxy0;
wire   [18:0] rhs_slice_proxy1;
wire   [15:0] slice_proxy0;
wire   [18:0] slice_proxy1;
wire   [15:0] slice_proxy2;
wire   [18:0] slice_proxy3;

//------------------------------------------------------------------------------
// Combinatorial Logic
//------------------------------------------------------------------------------

assign o_stream0_v = i_stream0_v;
assign o_stream0_i = (((((complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy0[15] != complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy2[14]) | (complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy4[15] != complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy6[13])) | (complexslicelowerer_complexslicelowerer_slice_proxy0[15] != complexslicelowerer_complexslicelowerer_slice_proxy1[12])) | (complexslicelowerer_slice_proxy0[15] != complexslicelowerer_slice_proxy1[11])) ? (slice_proxy0[15] ? 12'd4095 : 1'd0) : slice_proxy1[15:4]);
assign o_stream0_q = (((((complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy8[15] != complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy10[14]) | (complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy12[15] != complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy14[13])) | (complexslicelowerer_complexslicelowerer_slice_proxy2[15] != complexslicelowerer_complexslicelowerer_slice_proxy3[12])) | (complexslicelowerer_slice_proxy2[15] != complexslicelowerer_slice_proxy3[11])) ? (slice_proxy2[15] ? 12'd4095 : 1'd0) : slice_proxy3[15:4]);
assign firgain_0i_d_delay = i_stream0_i[11:0];
assign firgain_0i_mul_int0 = (firgain_0i_d_delay * firgain_0i_tap_c0);
assign firgain_0i_mul_int1 = (firgain_0i_ndelay0 * firgain_0i_tap_c1);
assign firgain_0i_mul_int2 = (firgain_0i_ndelay1 * firgain_0i_tap_c2);
assign firgain_0i_mul_int3 = (firgain_0i_ndelay2 * firgain_0i_tap_c3);
assign firgain_0i_mul_int4 = (firgain_0i_ndelay3 * firgain_0i_tap_c4);
assign firgain_0i_mul_int5 = (firgain_0i_ndelay4 * firgain_0i_tap_c5);
assign firgain_0i_mul_int6 = (firgain_0i_ndelay5 * firgain_0i_tap_c6);
assign firgain_0i_mul_int7 = (firgain_0i_ndelay6 * firgain_0i_tap_c7);
assign firgain_0i_mul_int8 = (firgain_0i_ndelay7 * firgain_0i_tap_c8);
assign firgain_0i_mul_int9 = (firgain_0i_ndelay8 * firgain_0i_tap_c9);
assign firgain_0i_mul_int10 = (firgain_0i_ndelay9 * firgain_0i_tap_c10);
assign firgain_0i_mul_int11 = (firgain_0i_ndelay10 * firgain_0i_tap_c11);
assign firgain_0i_mul_int12 = (firgain_0i_ndelay11 * firgain_0i_tap_c12);
assign firgain_0i_mul_int13 = (firgain_0i_ndelay12 * firgain_0i_tap_c13);
assign firgain_0i_mul_int14 = (firgain_0i_ndelay13 * firgain_0i_tap_c14);
assign firgain_0q_d_delay = i_stream0_q[11:0];
assign firgain_0q_mul_int0 = (firgain_0q_d_delay * firgain_0q_tap_c0);
assign firgain_0q_mul_int1 = (firgain_0q_ndelay0 * firgain_0q_tap_c1);
assign firgain_0q_mul_int2 = (firgain_0q_ndelay1 * firgain_0q_tap_c2);
assign firgain_0q_mul_int3 = (firgain_0q_ndelay2 * firgain_0q_tap_c3);
assign firgain_0q_mul_int4 = (firgain_0q_ndelay3 * firgain_0q_tap_c4);
assign firgain_0q_mul_int5 = (firgain_0q_ndelay4 * firgain_0q_tap_c5);
assign firgain_0q_mul_int6 = (firgain_0q_ndelay5 * firgain_0q_tap_c6);
assign firgain_0q_mul_int7 = (firgain_0q_ndelay6 * firgain_0q_tap_c7);
assign firgain_0q_mul_int8 = (firgain_0q_ndelay7 * firgain_0q_tap_c8);
assign firgain_0q_mul_int9 = (firgain_0q_ndelay8 * firgain_0q_tap_c9);
assign firgain_0q_mul_int10 = (firgain_0q_ndelay9 * firgain_0q_tap_c10);
assign firgain_0q_mul_int11 = (firgain_0q_ndelay10 * firgain_0q_tap_c11);
assign firgain_0q_mul_int12 = (firgain_0q_ndelay11 * firgain_0q_tap_c12);
assign firgain_0q_mul_int13 = (firgain_0q_ndelay12 * firgain_0q_tap_c13);
assign firgain_0q_mul_int14 = (firgain_0q_ndelay13 * firgain_0q_tap_c14);
assign complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy1 = firgain_0i_nq_sum4[18:0];
assign complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy0 = complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy1[18:3];
assign complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy3 = firgain_0i_nq_sum4[18:0];
assign complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy2 = complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy3[18:3];
assign complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy5 = firgain_0i_nq_sum4[18:0];
assign complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy4 = complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy5[18:3];
assign complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy7 = firgain_0i_nq_sum4[18:0];
assign complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy6 = complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy7[18:3];
assign complexslicelowerer_complexslicelowerer_rhs_slice_proxy0 = firgain_0i_nq_sum4[18:0];
assign complexslicelowerer_complexslicelowerer_slice_proxy0 = complexslicelowerer_complexslicelowerer_rhs_slice_proxy0[18:3];
assign complexslicelowerer_complexslicelowerer_rhs_slice_proxy1 = firgain_0i_nq_sum4[18:0];
assign complexslicelowerer_complexslicelowerer_slice_proxy1 = complexslicelowerer_complexslicelowerer_rhs_slice_proxy1[18:3];
assign complexslicelowerer_rhs_slice_proxy0 = firgain_0i_nq_sum4[18:0];
assign complexslicelowerer_slice_proxy0 = complexslicelowerer_rhs_slice_proxy0[18:3];
assign complexslicelowerer_rhs_slice_proxy1 = firgain_0i_nq_sum4[18:0];
assign complexslicelowerer_slice_proxy1 = complexslicelowerer_rhs_slice_proxy1[18:3];
assign rhs_slice_proxy0 = firgain_0i_nq_sum4[18:0];
assign slice_proxy0 = rhs_slice_proxy0[18:3];
assign slice_proxy1 = firgain_0i_nq_sum4[18:0];
assign complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy9 = firgain_0q_nq_sum4[18:0];
assign complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy8 = complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy9[18:3];
assign complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy11 = firgain_0q_nq_sum4[18:0];
assign complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy10 = complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy11[18:3];
assign complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy13 = firgain_0q_nq_sum4[18:0];
assign complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy12 = complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy13[18:3];
assign complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy15 = firgain_0q_nq_sum4[18:0];
assign complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy14 = complexslicelowerer_complexslicelowerer_complexslicelowerer_slice_proxy15[18:3];
assign complexslicelowerer_complexslicelowerer_rhs_slice_proxy2 = firgain_0q_nq_sum4[18:0];
assign complexslicelowerer_complexslicelowerer_slice_proxy2 = complexslicelowerer_complexslicelowerer_rhs_slice_proxy2[18:3];
assign complexslicelowerer_complexslicelowerer_rhs_slice_proxy3 = firgain_0q_nq_sum4[18:0];
assign complexslicelowerer_complexslicelowerer_slice_proxy3 = complexslicelowerer_complexslicelowerer_rhs_slice_proxy3[18:3];
assign complexslicelowerer_rhs_slice_proxy2 = firgain_0q_nq_sum4[18:0];
assign complexslicelowerer_slice_proxy2 = complexslicelowerer_rhs_slice_proxy2[18:3];
assign complexslicelowerer_rhs_slice_proxy3 = firgain_0q_nq_sum4[18:0];
assign complexslicelowerer_slice_proxy3 = complexslicelowerer_rhs_slice_proxy3[18:3];
assign rhs_slice_proxy1 = firgain_0q_nq_sum4[18:0];
assign slice_proxy2 = rhs_slice_proxy1[18:3];
assign slice_proxy3 = firgain_0q_nq_sum4[18:0];


//------------------------------------------------------------------------------
// Synchronous Logic
//------------------------------------------------------------------------------

always @(posedge clock) begin
    o_stream1_v <= i_stream1_v;
    o_stream1_i <= i_stream1_i;
    o_stream1_q <= i_stream1_q;
    if (i_stream0_v) begin
        firgain_0i_ndelay0 <= firgain_0i_d_delay;
    end
    if (i_stream0_v) begin
        firgain_0i_mul_q0 <= firgain_0i_mul_int0[27:8];
    end
    if (i_stream0_v) begin
        firgain_0i_ndelay1 <= firgain_0i_ndelay0;
    end
    if (i_stream0_v) begin
        firgain_0i_mul_q1 <= firgain_0i_mul_int1[27:8];
    end
    if (i_stream0_v) begin
        firgain_0i_ndelay2 <= firgain_0i_ndelay1;
    end
    if (i_stream0_v) begin
        firgain_0i_mul_q2 <= firgain_0i_mul_int2[27:8];
    end
    if (i_stream0_v) begin
        firgain_0i_ndelay3 <= firgain_0i_ndelay2;
    end
    if (i_stream0_v) begin
        firgain_0i_mul_q3 <= firgain_0i_mul_int3[27:8];
    end
    if (i_stream0_v) begin
        firgain_0i_ndelay4 <= firgain_0i_ndelay3;
    end
    if (i_stream0_v) begin
        firgain_0i_mul_q4 <= firgain_0i_mul_int4[27:8];
    end
    if (i_stream0_v) begin
        firgain_0i_ndelay5 <= firgain_0i_ndelay4;
    end
    if (i_stream0_v) begin
        firgain_0i_mul_q5 <= firgain_0i_mul_int5[27:8];
    end
    if (i_stream0_v) begin
        firgain_0i_ndelay6 <= firgain_0i_ndelay5;
    end
    if (i_stream0_v) begin
        firgain_0i_mul_q6 <= firgain_0i_mul_int6[27:8];
    end
    if (i_stream0_v) begin
        firgain_0i_ndelay7 <= firgain_0i_ndelay6;
    end
    if (i_stream0_v) begin
        firgain_0i_mul_q7 <= firgain_0i_mul_int7[27:8];
    end
    if (i_stream0_v) begin
        firgain_0i_ndelay8 <= firgain_0i_ndelay7;
    end
    if (i_stream0_v) begin
        firgain_0i_mul_q8 <= firgain_0i_mul_int8[27:8];
    end
    if (i_stream0_v) begin
        firgain_0i_ndelay9 <= firgain_0i_ndelay8;
    end
    if (i_stream0_v) begin
        firgain_0i_mul_q9 <= firgain_0i_mul_int9[27:8];
    end
    if (i_stream0_v) begin
        firgain_0i_ndelay10 <= firgain_0i_ndelay9;
    end
    if (i_stream0_v) begin
        firgain_0i_mul_q10 <= firgain_0i_mul_int10[27:8];
    end
    if (i_stream0_v) begin
        firgain_0i_ndelay11 <= firgain_0i_ndelay10;
    end
    if (i_stream0_v) begin
        firgain_0i_mul_q11 <= firgain_0i_mul_int11[27:8];
    end
    if (i_stream0_v) begin
        firgain_0i_ndelay12 <= firgain_0i_ndelay11;
    end
    if (i_stream0_v) begin
        firgain_0i_mul_q12 <= firgain_0i_mul_int12[27:8];
    end
    if (i_stream0_v) begin
        firgain_0i_ndelay13 <= firgain_0i_ndelay12;
    end
    if (i_stream0_v) begin
        firgain_0i_mul_q13 <= firgain_0i_mul_int13[27:8];
    end
    if (i_stream0_v) begin
        firgain_0i_ndelay14 <= firgain_0i_ndelay13;
    end
    if (i_stream0_v) begin
        firgain_0i_mul_q14 <= firgain_0i_mul_int14[27:8];
    end
    if (i_stream0_v) begin
        firgain_0i_nq_sum0 <= (((((((((((((((1'd0 + {1'd1, firgain_0i_mul_q0}) + {1'd1, firgain_0i_mul_q1}) + {1'd1, firgain_0i_mul_q2}) + {1'd1, firgain_0i_mul_q3}) + {1'd1, firgain_0i_mul_q4}) + {1'd1, firgain_0i_mul_q5}) + {1'd1, firgain_0i_mul_q6}) + {1'd1, firgain_0i_mul_q7}) + {1'd1, firgain_0i_mul_q8}) + {1'd1, firgain_0i_mul_q9}) + {1'd1, firgain_0i_mul_q10}) + {1'd1, firgain_0i_mul_q11}) + {1'd1, firgain_0i_mul_q12}) + {1'd1, firgain_0i_mul_q13}) + {1'd1, firgain_0i_mul_q14});
    end
    if (i_stream0_v) begin
        firgain_0i_nq_sum1 <= firgain_0i_nq_sum0[18:0];
    end
    if (i_stream0_v) begin
        firgain_0i_nq_sum2 <= firgain_0i_nq_sum1[18:0];
    end
    if (i_stream0_v) begin
        firgain_0i_nq_sum3 <= firgain_0i_nq_sum2[18:0];
    end
    if (i_stream0_v) begin
        firgain_0i_nq_sum4 <= firgain_0i_nq_sum3[18:0];
    end
    if (i_stream0_v) begin
        firgain_0q_ndelay0 <= firgain_0q_d_delay;
    end
    if (i_stream0_v) begin
        firgain_0q_mul_q0 <= firgain_0q_mul_int0[27:8];
    end
    if (i_stream0_v) begin
        firgain_0q_ndelay1 <= firgain_0q_ndelay0;
    end
    if (i_stream0_v) begin
        firgain_0q_mul_q1 <= firgain_0q_mul_int1[27:8];
    end
    if (i_stream0_v) begin
        firgain_0q_ndelay2 <= firgain_0q_ndelay1;
    end
    if (i_stream0_v) begin
        firgain_0q_mul_q2 <= firgain_0q_mul_int2[27:8];
    end
    if (i_stream0_v) begin
        firgain_0q_ndelay3 <= firgain_0q_ndelay2;
    end
    if (i_stream0_v) begin
        firgain_0q_mul_q3 <= firgain_0q_mul_int3[27:8];
    end
    if (i_stream0_v) begin
        firgain_0q_ndelay4 <= firgain_0q_ndelay3;
    end
    if (i_stream0_v) begin
        firgain_0q_mul_q4 <= firgain_0q_mul_int4[27:8];
    end
    if (i_stream0_v) begin
        firgain_0q_ndelay5 <= firgain_0q_ndelay4;
    end
    if (i_stream0_v) begin
        firgain_0q_mul_q5 <= firgain_0q_mul_int5[27:8];
    end
    if (i_stream0_v) begin
        firgain_0q_ndelay6 <= firgain_0q_ndelay5;
    end
    if (i_stream0_v) begin
        firgain_0q_mul_q6 <= firgain_0q_mul_int6[27:8];
    end
    if (i_stream0_v) begin
        firgain_0q_ndelay7 <= firgain_0q_ndelay6;
    end
    if (i_stream0_v) begin
        firgain_0q_mul_q7 <= firgain_0q_mul_int7[27:8];
    end
    if (i_stream0_v) begin
        firgain_0q_ndelay8 <= firgain_0q_ndelay7;
    end
    if (i_stream0_v) begin
        firgain_0q_mul_q8 <= firgain_0q_mul_int8[27:8];
    end
    if (i_stream0_v) begin
        firgain_0q_ndelay9 <= firgain_0q_ndelay8;
    end
    if (i_stream0_v) begin
        firgain_0q_mul_q9 <= firgain_0q_mul_int9[27:8];
    end
    if (i_stream0_v) begin
        firgain_0q_ndelay10 <= firgain_0q_ndelay9;
    end
    if (i_stream0_v) begin
        firgain_0q_mul_q10 <= firgain_0q_mul_int10[27:8];
    end
    if (i_stream0_v) begin
        firgain_0q_ndelay11 <= firgain_0q_ndelay10;
    end
    if (i_stream0_v) begin
        firgain_0q_mul_q11 <= firgain_0q_mul_int11[27:8];
    end
    if (i_stream0_v) begin
        firgain_0q_ndelay12 <= firgain_0q_ndelay11;
    end
    if (i_stream0_v) begin
        firgain_0q_mul_q12 <= firgain_0q_mul_int12[27:8];
    end
    if (i_stream0_v) begin
        firgain_0q_ndelay13 <= firgain_0q_ndelay12;
    end
    if (i_stream0_v) begin
        firgain_0q_mul_q13 <= firgain_0q_mul_int13[27:8];
    end
    if (i_stream0_v) begin
        firgain_0q_ndelay14 <= firgain_0q_ndelay13;
    end
    if (i_stream0_v) begin
        firgain_0q_mul_q14 <= firgain_0q_mul_int14[27:8];
    end
    if (i_stream0_v) begin
        firgain_0q_nq_sum0 <= (((((((((((((((1'd0 + {1'd1, firgain_0q_mul_q0}) + {1'd1, firgain_0q_mul_q1}) + {1'd1, firgain_0q_mul_q2}) + {1'd1, firgain_0q_mul_q3}) + {1'd1, firgain_0q_mul_q4}) + {1'd1, firgain_0q_mul_q5}) + {1'd1, firgain_0q_mul_q6}) + {1'd1, firgain_0q_mul_q7}) + {1'd1, firgain_0q_mul_q8}) + {1'd1, firgain_0q_mul_q9}) + {1'd1, firgain_0q_mul_q10}) + {1'd1, firgain_0q_mul_q11}) + {1'd1, firgain_0q_mul_q12}) + {1'd1, firgain_0q_mul_q13}) + {1'd1, firgain_0q_mul_q14});
    end
    if (i_stream0_v) begin
        firgain_0q_nq_sum1 <= firgain_0q_nq_sum0[18:0];
    end
    if (i_stream0_v) begin
        firgain_0q_nq_sum2 <= firgain_0q_nq_sum1[18:0];
    end
    if (i_stream0_v) begin
        firgain_0q_nq_sum3 <= firgain_0q_nq_sum2[18:0];
    end
    if (i_stream0_v) begin
        firgain_0q_nq_sum4 <= firgain_0q_nq_sum3[18:0];
    end
    if (reset) begin
        o_stream1_v <= 1'd0;
        o_stream1_i <= 16'd0;
        o_stream1_q <= 16'd0;
        firgain_0i_ndelay0 <= 12'd0;
        firgain_0i_mul_q0 <= 20'd0;
        firgain_0i_ndelay1 <= 12'd0;
        firgain_0i_mul_q1 <= 20'd0;
        firgain_0i_ndelay2 <= 12'd0;
        firgain_0i_mul_q2 <= 20'd0;
        firgain_0i_ndelay3 <= 12'd0;
        firgain_0i_mul_q3 <= 20'd0;
        firgain_0i_ndelay4 <= 12'd0;
        firgain_0i_mul_q4 <= 20'd0;
        firgain_0i_ndelay5 <= 12'd0;
        firgain_0i_mul_q5 <= 20'd0;
        firgain_0i_ndelay6 <= 12'd0;
        firgain_0i_mul_q6 <= 20'd0;
        firgain_0i_ndelay7 <= 12'd0;
        firgain_0i_mul_q7 <= 20'd0;
        firgain_0i_ndelay8 <= 12'd0;
        firgain_0i_mul_q8 <= 20'd0;
        firgain_0i_ndelay9 <= 12'd0;
        firgain_0i_mul_q9 <= 20'd0;
        firgain_0i_ndelay10 <= 12'd0;
        firgain_0i_mul_q10 <= 20'd0;
        firgain_0i_ndelay11 <= 12'd0;
        firgain_0i_mul_q11 <= 20'd0;
        firgain_0i_ndelay12 <= 12'd0;
        firgain_0i_mul_q12 <= 20'd0;
        firgain_0i_ndelay13 <= 12'd0;
        firgain_0i_mul_q13 <= 20'd0;
        firgain_0i_ndelay14 <= 12'd0;
        firgain_0i_mul_q14 <= 20'd0;
        firgain_0i_nq_sum0 <= 20'd0;
        firgain_0i_nq_sum1 <= 20'd0;
        firgain_0i_nq_sum2 <= 20'd0;
        firgain_0i_nq_sum3 <= 20'd0;
        firgain_0i_nq_sum4 <= 20'd0;
        firgain_0q_ndelay0 <= 12'd0;
        firgain_0q_mul_q0 <= 20'd0;
        firgain_0q_ndelay1 <= 12'd0;
        firgain_0q_mul_q1 <= 20'd0;
        firgain_0q_ndelay2 <= 12'd0;
        firgain_0q_mul_q2 <= 20'd0;
        firgain_0q_ndelay3 <= 12'd0;
        firgain_0q_mul_q3 <= 20'd0;
        firgain_0q_ndelay4 <= 12'd0;
        firgain_0q_mul_q4 <= 20'd0;
        firgain_0q_ndelay5 <= 12'd0;
        firgain_0q_mul_q5 <= 20'd0;
        firgain_0q_ndelay6 <= 12'd0;
        firgain_0q_mul_q6 <= 20'd0;
        firgain_0q_ndelay7 <= 12'd0;
        firgain_0q_mul_q7 <= 20'd0;
        firgain_0q_ndelay8 <= 12'd0;
        firgain_0q_mul_q8 <= 20'd0;
        firgain_0q_ndelay9 <= 12'd0;
        firgain_0q_mul_q9 <= 20'd0;
        firgain_0q_ndelay10 <= 12'd0;
        firgain_0q_mul_q10 <= 20'd0;
        firgain_0q_ndelay11 <= 12'd0;
        firgain_0q_mul_q11 <= 20'd0;
        firgain_0q_ndelay12 <= 12'd0;
        firgain_0q_mul_q12 <= 20'd0;
        firgain_0q_ndelay13 <= 12'd0;
        firgain_0q_mul_q13 <= 20'd0;
        firgain_0q_ndelay14 <= 12'd0;
        firgain_0q_mul_q14 <= 20'd0;
        firgain_0q_nq_sum0 <= 20'd0;
        firgain_0q_nq_sum1 <= 20'd0;
        firgain_0q_nq_sum2 <= 20'd0;
        firgain_0q_nq_sum3 <= 20'd0;
        firgain_0q_nq_sum4 <= 20'd0;
    end
end


//------------------------------------------------------------------------------
// Specialized Logic
//------------------------------------------------------------------------------

endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2025-11-29 14:35:46.
//------------------------------------------------------------------------------
